// <auto-generated />
namespace OpenSourceTees.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BlobStorage13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlobStorage13));
        
        string IMigrationMetadata.Id
        {
            get { return "201901200455211_BlobStorage1.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
